# Dockerfile pour entraîner un modèle MLflow
FROM python:3.11-slim

WORKDIR /app

# Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier les fichiers
COPY trainer.py .
COPY iris.csv .

# Script à lancer automatiquement
CMD ["python", "trainer.py"]
